version: '3.7'
services:
  capture:
    user: node
    build: capture
    volumes:
      - ./capture:/node/app
      - ./result:/node/result
    environment:
      LOG_LEVEL: info
      LOG_COLOR: 'true'
    init: true
    tty: true
    ulimits:
      memlock: -1
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "5"

